# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI (experimental)
on:
  push:
    branches:
      - main
  pull_request:
  # schedule:
  #   # https://crontab.guru/#0_12_*_*_0
  #   - cron: 0 12 * * 0 # At 12:00 on Sunday

env:
  GO_VERSION: ^1.22.0

jobs:
  affected:
    name: Finding affected tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      nodejs-paths: ${{ steps.nodejs.outputs.paths }}
      nodejs-setups: ${{ steps.nodejs.outputs.setups }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go build -o ${{ github.workspace }}/tools ./cmd/...
        working-directory: .github/cloud-samples-tools
      - name: Get diffs
        run: git --no-pager diff --name-only HEAD origin/main | tee diffs.txt
      - name: Find Node.js affected packages
        id: nodejs
        run: |
          echo "paths=$(./tools affected .github/config/nodejs-dev.jsonc diffs.txt paths.txt)" >> $GITHUB_OUTPUT
          cat paths.txt
          echo "setups=$(./tools setup-files .github/config/nodejs-dev.jsonc paths.txt)" >> $GITHUB_OUTPUT

  nodejs-test:
    name: Node.js test
    needs: affected
    runs-on: ubuntu-latest
    timeout-minutes: 120 # 2 hours hard limit
    permissions:
      id-token: write # needed for google-github-actions/auth
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(github.event_name == 'pull_request' && needs.affected.outputs.nodejs-paths || '[]') }}
    env:
      CI_SETUP: ${{ toJson(fromJson(needs.affected.outputs.nodejs-setups)[matrix.path])}}
    steps:
      - name: CI Setup
        run: echo "${{ env.CI_SETUP }}"
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: ${{ fromJson(env.CI_SETUP).node-version }}
      - uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2
        with:
          project_id: ${{ fromJson(env.CI_SETUP).project-id }}
          workload_identity_provider: ${{ fromJson(env.CI_SETUP).workload-identity-provider }}
          service_account: ${{ fromJson(env.CI_SETUP).service-account }}
          access_token_lifetime: ${{ fromJson(env.CI_SETUP).access-token-lifetime }}
      - name: Export environment variables
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        id: vars
        with:
          script: |
            const { default: setupVars } = await import('${{ github.workspace }}/.github/scripts/vars-setup.js')

            const setup = JSON.parse(process.env.CI_SETUP);
            return await setupVars({core, setup})

      - uses: google-github-actions/get-secretmanager-secrets@e5bb06c2ca53b244f978d33348d18317a7f263ce # v2
        if: ${{ fromJson(steps.vars.outputs.result).secrets }}
        with:
          secrets: ${{ fromJson(steps.vars.outputs.result).secrets }}
          export_to_environment: true
      - name: üõ†Ô∏è Test ${{ matrix.path }}
        run: |
          timeout ${{ fromJson(env.CI_SETUP).timeout-minutes }}m \
            make test dir=${{ matrix.path }}
